### PR TITLE
Feature: add molecule scenario to test find with emtpy folder

### PR DESCRIPTION
**Pull request by rsicart**
## Description
Add molecule scenario to test find with an emtpy folder, or a folder which does not contain war/jar files.

## Motivation and Context
To reduce perfomance impact on remote servers or just analyse `lsof` related files.

## How Has This Been Tested?

I created a molecule scenario which downloads vulnerable files, which are ignored because of `log4shell_find_enabled` flag set to `false`.

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ElieDeloumeau** [comment]
Is it really useful? I mean, you can set `log4shell_scan_path` to an empty (or almost) directory like /tmp and the result will be the same?

**Comment by ElieDeloumeau** [comment]
> Yes you're right.

Good 😃 on the other hand, your tests are interesting.

Could you please remove the flag `log4shell_find_enabled`, change your tests to use `log4shell_scan_path: /opt` and change the PR title/description?

**Comment by rsicart** [comment]
My tests are already using `log4shell_scan_path: /opt`. Do you mean testing a folder which does not contain war/jar files?

**Review by ElieDeloumeau — APPROVED** [review]
LGTM

**Pull request merged**
